Sprint5
OlegMzhelskiy/gophermart pull request #1
Opened 2022-10-01 22:16 UTC by OlegMzhelskiy

2022-10-04 10:56 UTC, rktkov requested changes

2022-10-04 10:56 UTC, rktkov commented on pkg/validate.go
> +	//fmt.Printf("\nsum: %d\n", sum)
Весь не используемый код надо удалять.

2022-10-04 10:56 UTC, rktkov commented on internal/usecase/order.go
> +	ProcessingOrders []models.OrderNumber
Что-то я не пойму зачем нужен этот слайс.
Можешь в комментарии написать где и зачем он используется, еще и как открытое поле. Было бы интересно узнать, какие внутрение задачи он решает, и как используется во вне.

2022-10-04 10:56 UTC, rktkov commented on internal/usecase/order.go
> +	request := models.AccrualRequest{}
Я бы взаимодействие с внешним сервисом убрал бы за интерфейс и вынес бы реализацию в отдельный пакет.

2022-10-04 11:33 UTC, OlegMzhelskiy commented on internal/usecase/order.go
> +	ProcessingOrders []models.OrderNumber
Этот слайс хранит номера заказов по которым еще не получен конечный статус из Accrual-сервиса.
Функция WorkerGettingOrderStatus из пакета usecase по таймеру опрашивает Accrual-сервис на получение статусов заказов из этого слайса. Если в ответ от Accrual-сервиса мы получили статус Invalid или Processed то номер заказа удаляется из слайса.
В этой же функции и происходит добавление номера заказа в слайс при регистрации нового заказа.

2022-10-13 08:13 UTC, rktkov approved these changes

2022-11-22 21:16 UTC, merged